name: MUHAMMAD ALZUHAIRY

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "ğ˜‘ğ˜”ğ˜›ğ˜ğ˜–ğ˜•"

          replace: "ğ˜‘ğ˜Œğ˜Œğ˜—ğ˜›ğ˜ğ˜–ğ˜•"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'by ~ RR7PP'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: RR9R7

          commit_user_email: roz@emtg.in
